version: '3'
services:
  backup:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: onhout/asctx-db-backup:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
    # command: tail -f /dev/null
    environment:
      - CRON_TIME="0 3 * * sun" 
      - MYSQL_HOST="mysql"
      - MYSQL_USER="root"
      - MYSQL_PASS="ASCthr12345"
      - POSTGRESQL_HOST="postgres"
    networks:
      - asc_database
    volumes:
      - mysql_backup_volume:/backup


volumes:
  mysql_backup_volume:
    driver: local
    driver_opts:
      type: cifs
      o: username=peter,password=ASCthr12345,rw,domain=asctherapeutics.com,uid=999,gid=999
      device: "\\\\192.168.168.1\\Web\\docker\\db_backup\\backups\\mysql"

networks:
  asc_database:
    external: true